# Generated by Django 4.0.4 on 2022-04-16 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_auther',
            field=models.BooleanField(default=False, verbose_name='وضعیت نویسنگی'),
        ),
        migrations.AddField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان کاربری ویژه'),
        ),
    ]
