# Generated by Django 4.0.4 on 2022-04-16 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_auther_user_special_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_auther',
            new_name='is_author',
        ),
    ]
